# Generated by Django 3.2.7 on 2021-10-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('second_name', models.CharField(max_length=100, null=True)),
                ('matric_no', models.CharField(max_length=100, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('lecture_1', models.BooleanField(default=True)),
                ('lecture_2', models.BooleanField(default=True)),
                ('lecture_3', models.BooleanField(default=True)),
                ('lecture_4', models.BooleanField(default=True)),
                ('lecture_5', models.BooleanField(default=True)),
                ('lecture_6', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
